'use client';
import {useState,useRef,useEffect,useCallback} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Sidebar,SidebarProvider,SidebarContent,SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Upload,ArrowUpRight,FileText,BookOpen,Sparkles,Plus,ChevronLeft,ChevronRight,Languages,ArrowUp,LoaderCircle,X,Quote,PanelRightOpen,Check,ScanText,Link2,StopCircle,Settings2} from 'lucide-react';
import Markdown from 'react-markdown';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import type {PDFDocumentProxy} from 'pdfjs-dist';
import {extractBlocks,fromText,splitText,groupBySections,type Paper,type Block,type ModelResult} from '@/lib/paper';
import 'katex/dist/katex.min.css';
type Message={role:'user'|'assistant';text:string;citations?:ModelResult['citations'];warnings?:string[];scope?:string};
type APIAction='translate'|'explain'|'ask'|'ocr';
const mdComponents={a:({children}:{children?:React.ReactNode})=><span>{children}</span>};
function RichText({text}:{text:string}){return <div className="rich-text"><Markdown remarkPlugins={[remarkMath]} rehypePlugins={[rehypeKatex]} components={mdComponents}>{text}</Markdown></div>}
export default function PaperReader(){
 const [paper,setPaper]=useState<Paper|null>(null),[page,setPage]=useState(0),[sourcePage,setSourcePage]=useState(1),[mode,setMode]=useState('both');
 const [importOpen,setImportOpen]=useState(false),[connectOpen,setConnectOpen]=useState(false),[mobileOpen,setMobileOpen]=useState(false);
 const [paste,setPaste]=useState(''),[pasteTitle,setPasteTitle]=useState(''),[drag,setDrag]=useState(false),[importing,setImporting]=useState(false),[importProgress,setImportProgress]=useState(0);
 const [provider,setProvider]=useState<'deepseek'|'openai'>('deepseek'),[apiKey,setApiKey]=useState(''),[configured,setConfigured]=useState<boolean|null>(null),[statusError,setStatusError]=useState(''),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 const [translations,setTranslations]=useState<Record<string,string>>({}),[pageNotes,setPageNotes]=useState<Record<number,string[]>>({}),[glossary,setGlossary]=useState<{term:string;translation:string}[]>([]);
 const [selected,setSelected]=useState<string[]>([]),[excerpt,setExcerpt]=useState<{text:string;ids:string[]}|null>(null),[pending,setPending]=useState<{text:string;ids:string[]}|null>(null);
 const [question,setQuestion]=useState(''),[messages,setMessages]=useState<Message[]>([]),[pageImage,setPageImage]=useState(''),[imageLoading,setImageLoading]=useState(false),[imageError,setImageError]=useState('');
 const pdfRef=useRef<PDFDocumentProxy|null>(null),urlRef=useRef(''),imageCache=useRef(new Map<number,string>()),abortRef=useRef<AbortController|null>(null),sessionRef=useRef(0),fileRef=useRef<HTMLInputElement|null>(null),chatEnd=useRef<HTMLDivElement|null>(null),glossaryRef=useRef(glossary),paperRef=useRef(paper),apiBusyRef=useRef(false);
 glossaryRef.current=glossary;paperRef.current=paper;
 const connected=Boolean(apiKey.trim())||(provider==='openai'&&configured===true);
 const current=paper?.pages[page],sourcePages=current?.sourcePages||[page+1],allBlocks=paper?.pages.flatMap(p=>p.blocks)||[];
 const chosen=excerpt?allBlocks.filter(b=>excerpt.ids.includes(b.id)):allBlocks.filter(b=>selected.includes(b.id));
 const selectedText=excerpt?.text||chosen.map(b=>`[第 ${b.page} 页 · ${b.id}]\n${b.text}`).join('\n\n');
 const completePages=paper?.pages.filter(p=>p.blocks.length>0&&p.blocks.every(b=>translations[b.id])).length||0;
 const checkConnection=useCallback(async()=>{setStatusError('');try{const r=await fetch('/api/status');if(!r.ok)throw new Error();const d=await r.json() as {configured:boolean};setConfigured(d.configured===true);}catch{setConfigured(null);setStatusError('连接状态获取失败，可以重试。');}},[]);
 useEffect(()=>{void checkConnection();return()=>{abortRef.current?.abort();if(urlRef.current)URL.revokeObjectURL(urlRef.current);void pdfRef.current?.loadingTask.destroy();};},[checkConnection]);
 useEffect(()=>{chatEnd.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[messages,busy]);
 useEffect(()=>{const listener=()=>{const s=window.getSelection();const anchor=s?.anchorNode?.parentElement?.closest('[data-paper-block]'),focus=s?.focusNode?.parentElement?.closest('[data-paper-block]');const text=s?.toString().trim();if(text&&anchor&&focus){const start=allBlocks.findIndex(b=>b.id===anchor.getAttribute('data-paper-block')),end=allBlocks.findIndex(b=>b.id===focus.getAttribute('data-paper-block'));setPending({text,ids:allBlocks.slice(Math.min(start,end),Math.max(start,end)+1).map(b=>b.id)});}else if(!text)setPending(null);};document.addEventListener('selectionchange',listener);return()=>document.removeEventListener('selectionchange',listener);},[paper]);
 const renderImage=useCallback(async(num:number)=>{const cached=imageCache.current.get(num);if(cached)return cached;const doc=pdfRef.current;if(!doc)return '';const pdfPage=await doc.getPage(num);const base=pdfPage.getViewport({scale:1});const viewport=pdfPage.getViewport({scale:Math.min(2,1400/base.width)});const canvas=document.createElement('canvas');canvas.width=Math.round(viewport.width);canvas.height=Math.round(viewport.height);const ctx=canvas.getContext('2d');if(!ctx)throw new Error('浏览器无法显示 PDF 页面。');await pdfPage.render({canvas,canvasContext:ctx,viewport}).promise;const data=canvas.toDataURL('image/jpeg',.86);canvas.width=0;canvas.height=0;if(pdfRef.current===doc){if(imageCache.current.size>3)imageCache.current.delete(imageCache.current.keys().next().value!);imageCache.current.set(num,data);}return data;},[]);
 useEffect(()=>{let valid=true;setPageImage('');setImageError('');if(!paper||paper.kind!=='pdf')return;setImageLoading(true);renderImage(sourcePage).then(data=>{if(valid)setPageImage(data);}).catch(()=>{if(valid)setImageError('原页预览加载失败，可点击“打开原 PDF”核对。');}).finally(()=>{if(valid)setImageLoading(false);});return()=>{valid=false;};},[paper?.url,paper?.title,paper?.kind,sourcePage,renderImage]);
 function reset(next:Paper){sessionRef.current++;abortRef.current?.abort();setPaper(next);setPage(0);setSourcePage(next.pages[0]?.sourcePages?.[0]||1);setTranslations({});setPageNotes({});setGlossary([]);setSelected([]);setExcerpt(null);setPending(null);setMessages([]);setQuestion('');setError('');setStatus('');setMode('both');setImportOpen(false);setMobileOpen(false);}
 async function importPDF(file:File){if(importing||busy)return;setError('');if(!/\.pdf$/i.test(file.name)&&file.type!=='application/pdf'){setError('请选择 PDF 文件，或切换到“粘贴原文”。');return;}if(file.size>20*1024*1024){setError('文件超过 20 MB，请压缩或拆分后导入。');return;}setImporting(true);setImportProgress(0);let doc:PDFDocumentProxy|null=null;try{const buffer=await file.arrayBuffer();const signature=new TextDecoder().decode(buffer.slice(0,1024));if(!signature.includes('%PDF-'))throw new Error('这不是有效的 PDF 文件。');const pdfjs=await import('pdfjs-dist');pdfjs.GlobalWorkerOptions.workerSrc='/pdfjs/pdf.worker.mjs';doc=await pdfjs.getDocument({data:new Uint8Array(buffer),cMapUrl:'/pdfjs/cmaps/',cMapPacked:true,standardFontDataUrl:'/pdfjs/standard_fonts/',wasmUrl:'/pdfjs/wasm/'}).promise;if(doc.numPages>100)throw new Error('当前支持最多 100 页的 PDF，请按章节拆分。');const pages:Paper['pages']=[];for(let i=1;i<=doc.numPages;i++){const p=await doc.getPage(i),content=await p.getTextContent();const items=content.items.filter((x):x is typeof x&{str:string;transform:number[];width:number;height:number}=>'str'in x);const blocks=extractBlocks(items,i,p.getViewport({scale:1}).width);const label=blocks.map(b=>b.text).find(t=>/^(abstract|introduction|conclusion|references|摘要|引言|结论|\d+(\.\d+)*\s+[A-Z])/i.test(t.trim())&&t.length<120);pages.push({number:i,label:label?.split('\n')[0].slice(0,50)||`第 ${i} 页`,blocks,scanned:blocks.reduce((n,b)=>n+b.text.trim().length,0)<30});setImportProgress(Math.round(i/doc.numPages*100));}
 const old=pdfRef.current;pdfRef.current=doc;doc=null;void old?.loadingTask.destroy();imageCache.current.clear();if(urlRef.current)URL.revokeObjectURL(urlRef.current);urlRef.current=URL.createObjectURL(file);reset({title:file.name.replace(/\.pdf$/i,''),pages:groupBySections(pages),url:urlRef.current,kind:'pdf'});
 }catch(e){await doc?.loadingTask.destroy();setError(e instanceof Error?(e.name==='PasswordException'?'此 PDF 已加密，请先解除密码保护再导入。':e.message):'PDF 读取失败，请换一个文件。');}finally{setImporting(false);}}
 function importText(){const text=paste.trim();if(!text){setError('请先粘贴论文内容。');return;}if(text.length>400000){setError('文本超过 40 万字符，请按章节导入。');return;}void pdfRef.current?.loadingTask.destroy();pdfRef.current=null;imageCache.current.clear();if(urlRef.current)URL.revokeObjectURL(urlRef.current);urlRef.current='';reset(fromText(text,pasteTitle));setPaste('');setPasteTitle('');}
 async function example(){setError('');try{const r=await fetch('/attention.pdf');if(!r.ok)throw new Error();await importPDF(new File([await r.blob()],'Attention Is All You Need.pdf',{type:'application/pdf'}));}catch{setError('示例加载失败，请直接上传论文。');}}
 function toggleBlock(id:string,on:boolean){setExcerpt(null);setSelected(old=>on?[...new Set([...old,id])]:old.filter(x=>x!==id));}
 function selectExcerpt(){if(!pending)return;setExcerpt(pending);setSelected([]);setPending(null);window.getSelection()?.removeAllRanges();if(window.innerWidth<931)setMobileOpen(true);}
 function clearSelection(){setSelected([]);setExcerpt(null);setPending(null);}
 function goTo(index:number,id?:string){setPage(index);setSourcePage(paper?.pages[index]?.sourcePages?.[0]||index+1);setPending(null);setMobileOpen(false);window.scrollTo({top:0,behavior:'smooth'});if(id)setTimeout(()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'center'}),160);}
 function requireConnection(){if(!connected){setConnectOpen(true);return false;}return true;}
 async function request(action:APIAction,blocks:Block[],q:string,selection:string,controller:AbortController,history:Message[]=[]):Promise<ModelResult>{const thisPaper=paperRef.current;if(!thisPaper)throw new Error('请先导入论文。');const nums=[...new Set(blocks.map(b=>b.page))];if(action==='ocr'&&!nums.length)nums.push(sourcePage);const images=[];if(thisPaper.kind==='pdf'){for(const n of nums.slice(0,3)){const data=await renderImage(n);if(data)images.push({page:n,data});}}if(controller.signal.aborted)throw new DOMException('Cancelled','AbortError');const res=await fetch('/api/assist',{method:'POST',headers:{'Content-Type':'application/json','X-AI-Provider':provider,...(apiKey.trim()?{'X-AI-API-Key':apiKey.trim()}:{})},signal:controller.signal,body:JSON.stringify({action,blocks,question:q,selected:selection,images,title:thisPaper.title,glossary:glossaryRef.current,history:history.slice(-8).map(m=>({role:m.role,text:m.text.slice(0,16000)}))})});const data=await res.json() as ModelResult & {error?:string};if(!res.ok){if(res.status===503&&!apiKey.trim())setConfigured(false);throw new Error(data.error||'请求失败，请重试。');}return data;}
 function begin(){apiBusyRef.current=true;setBusy(true);setError('');const c=new AbortController();abortRef.current=c;return c;}
 function finish(){apiBusyRef.current=false;setBusy(false);abortRef.current=null;}
 function handleError(e:unknown){if(e instanceof Error&&e.name==='AbortError'){setStatus('已停止。已完成的内容仍保留。');return;}setError(e instanceof Error?e.message:'处理失败，请稍后重试。');setStatus('');}
 function mergeResult(result:ModelResult,num:number){setTranslations(old=>({...old,...Object.fromEntries(result.translations.map(t=>[t.id,t.text]))}));setPageNotes(old=>({...old,[num]:[...new Set([...(old[num]||[]),...result.warnings])]}));if(result.glossary.length){const map=new Map(glossaryRef.current.map(g=>[g.term.toLowerCase(),g]));for(const g of result.glossary)if(!map.has(g.term.toLowerCase()))map.set(g.term.toLowerCase(),g);const next=[...map.values()].slice(0,80);glossaryRef.current=next;setGlossary(next);}}
 async function translate(all=false){if(apiBusyRef.current||!paper||!current||!requireConnection())return;const c=begin();try{const targets=all?paper.pages:[current];for(const p of targets){if(c.signal.aborted)break;if(!p.blocks.length)throw new Error(`「${p.label}」没有足够可选文字。请先识别对应原页。`);const remaining=p.blocks.filter(b=>!translations[b.id]);let batch:Block[]=[];let count=0;const batches:Block[][]=[];for(const b of remaining){if((count+b.text.length>5500||batch.length>=90)&&batch.length){batches.push(batch);batch=[];count=0;}batch.push(b);count+=b.text.length;}if(batch.length)batches.push(batch);for(let i=0;i<batches.length;i++){setStatus(`正在翻译第 ${p.number} / ${paper.pages.length} 节 · ${i+1}/${batches.length} 批`);const result=await request('translate',batches[i],'忠实、完整地逐段翻译为简体中文。','',c);mergeResult(result,p.number);} }setStatus(c.signal.aborted?'已停止，已完成译文保留。':all?'全文翻译完成。请对照原文核对公式、数值与注释。':'本页翻译完成。');}catch(e){handleError(e);}finally{finish();}}
 async function ocr(){if(apiBusyRef.current||!current||!requireConnection())return;const c=begin();setStatus('正在识别本页文字…');try{const result=await request('ocr',[],'按原始阅读顺序识别当前页全部文字。','',c);const blocks=result.transcript.flatMap(splitText).filter(t=>t.trim()).map((text,i)=>({id:`p${sourcePage}-ocr${i+1}`,text,page:sourcePage}));setPaper(old=>old?{...old,pages:old.pages.map((p,i)=>i===page?{...p,blocks:[...p.blocks.filter(b=>b.page!==sourcePage),...blocks].sort((a,b)=>a.page-b.page),scanned:false}:p)}:old);setPageNotes(old=>({...old,[page+1]:['本页为 AI 文字识别结果，请与原页核对后翻译。',...result.warnings]}));setStatus('文字识别完成，请核对原页。');}catch(e){handleError(e);}finally{finish();}}
 async function ask(kind:'ask'|'explain',preset?:string){if(apiBusyRef.current||!paper||!current)return;const q=preset||question.trim();if(kind==='ask'&&!q)return;if(!requireConnection())return;const scopePages=[...new Set([...sourcePages,...chosen.map(b=>b.page)])].sort((a,b)=>a-b);const blocks=[...new Map([...current.blocks,...chosen].map(b=>[b.id,b])).values()];if(!blocks.length){setError('当前页没有可引用的文字，请先识别本页文字。');return;}if(blocks.reduce((n,b)=>n+b.text.length,0)>48000||selectedText.length>16000){setError('引用内容过多，请减少勾选段落后再试。');return;}const c=begin();const prompt=q||'请讲解这一节的核心内容、关键术语与必要的数学细节。';setMessages(old=>[...old,{role:'user',text:prompt,scope:`依据第 ${scopePages.join('、')} 页${selectedText?'与所选片段':''}`}]);setQuestion('');setStatus('正在结合原文回答…');try{const result=await request(kind,blocks,prompt,selectedText,c,messages);setMessages(old=>[...old,{role:'assistant',text:result.answer,citations:result.citations,warnings:result.warnings,scope:`依据「${current.label}」及第 ${scopePages.join('、')} 页选段`}]);setStatus('');}catch(e){handleError(e);setQuestion(prompt);}finally{finish();}}
 function stop(){abortRef.current?.abort();}
 function showPanel(){setMobileOpen(true);}
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,opts:{signal:AbortSignal})=>Promise<void>}}).modelContext;if(!ctx?.registerTool)return;const ac=new AbortController();const tools=[{name:'read_paper_context',description:'读取已导入论文的可见页和段落编号，不调用 AI。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({title:paper?.title||null,page:page+1,totalPages:paper?.pages.length||0,blocks:current?.blocks||[],selected})},{name:'select_paper_passages',description:'用段落编号勾选论文内容供后续提问。不会发送 AI 请求。',inputSchema:{type:'object',properties:{ids:{type:'array',items:{type:'string'}}},required:['ids'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const ids=(input as {ids?:unknown})?.ids;if(!Array.isArray(ids)||!ids.every(id=>typeof id==='string'&&allBlocks.some(b=>b.id===id)))throw new Error('段落编号不存在');setExcerpt(null);setSelected([...new Set(ids)]);return {selected:[...new Set(ids)]};}}];for(const t of tools){try{void Promise.resolve(ctx.registerTool(t,{signal:ac.signal})).catch(()=>{});}catch{}}return()=>ac.abort();},[paper,page,selected]);
 const importForm=<Tabs defaultValue="file" className="import-tabs"><TabsList><TabsTrigger value="file">上传 PDF</TabsTrigger><TabsTrigger value="text">粘贴原文</TabsTrigger></TabsList><TabsContent value="file"><div className={`dropzone ${drag?'dragging':''} ${importing?'loading':''}`} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);const file=e.dataTransfer.files[0];if(file)void importPDF(file);}}>{importing?<LoaderCircle className="spin"/>:<Upload/>}<h2>{importing?'正在读取论文…':'放入你想读的论文'}</h2><p>{importing?`${importProgress}% · 逐页提取原文`:'拖拽 PDF 到这里，或点击选择文件'}</p><span className="file-limit">PDF · 最多 20 MB / 100 页</span><input ref={fileRef} disabled={importing||busy} type="file" accept="application/pdf,.pdf" aria-label="选择论文 PDF" onChange={e=>{const f=e.target.files?.[0];if(f)void importPDF(f);e.target.value='';}}/></div>{importing&&<Progress value={importProgress} aria-label="论文读取进度" className="mt-4 h-1"/>}<div className="sample-line"><span>手边没有论文？</span><button disabled={importing||busy} onClick={()=>void example()}>试读 Attention Is All You Need <ArrowUpRight size={14}/></button></div></TabsContent><TabsContent value="text"><label className="field-label" htmlFor="paper-title">论文标题（可选）</label><input id="paper-title" className="text-input" value={pasteTitle} maxLength={500} onChange={e=>setPasteTitle(e.target.value)} placeholder="为这次阅读起个名字"/><label className="field-label" htmlFor="paper-text">论文原文</label><textarea id="paper-text" rows={7} value={paste} onChange={e=>setPaste(e.target.value)} placeholder="粘贴摘要、章节或全文，用空行分隔段落。支持中英文，最多 40 万字符。"/><button className="primary import-button" disabled={!paste.trim()||busy||importing} onClick={importText}>开始阅读 <ArrowUpRight size={16}/></button></TabsContent></Tabs>;
 const panel=<><div className="panel-title"><Sparkles size={19}/><b>一起读懂</b><span>论文助手</span></div>{!paper?<div className="assistant-empty"><span className="spark-circle"><Sparkles size={28}/></span><h3>你的问题，值得展开。</h3><p>导入论文后，勾选段落或划选文字，<br/>在这里翻译、解释或继续追问。</p><span className="example-question">“这段结论需要哪些前提？” <ArrowUpRight size={15}/></span></div>:<><div className="panel-top">{error&&<div className="panel-error" role="alert">{error}</div>}<div className="selection-card"><div className="selection-header"><span><Quote size={13}/> {selectedText?`已引用 ${chosen.length} 段`:'引用原文'}</span>{selectedText&&<button aria-label="清除引用" onClick={clearSelection}><X size={14}/></button>}</div><p>{selectedText||'勾选段落左侧的方框，或直接划选你想问的文字。'}</p>{selectedText&&<small>第 {[...new Set(chosen.map(b=>b.page))].join('、')} 页 · 保留原文上下文</small>}</div><div className="quick-actions"><button disabled={busy} onClick={()=>void ask('explain','请用直觉解释所选内容；若无选段，则解释当前章节。')}><Sparkles size={14}/>通俗讲解</button><button disabled={busy} onClick={()=>void ask('ask','请解释这部分的公式，说明各个符号、维度和每一步的依据；若没有公式请直接说明。')}><span className="math-icon">ƒ</span>公式拆解</button></div></div><div className="chat-messages" aria-live="polite">{messages.length===0?<div className="chat-hint"><BookOpen size={20}/><h3>从一个具体问题开始</h3><p>例如：这个假设为什么成立？<br/>这一步推导省略了什么？</p><small>回答依据当前章节及引用段落。</small></div>:messages.map((m,i)=><div className={`message ${m.role}`} key={i}><div className="message-meta">{m.role==='user'?'你':'论文助手'}<span>{m.role==='assistant'?'AI 生成':''}</span></div><RichText text={m.text}/>{m.citations?.length? <div className="citations">{m.citations.map((c,j)=><button key={j} title={c.quote} onClick={()=>{const b=allBlocks.find(b=>b.id===c.id);if(b)goTo(paper.pages.findIndex(p=>p.blocks.some(x=>x.id===b.id)),b.id);}}><Link2 size={12}/>{c.id}</button>)}</div>:null}{m.warnings?.map((w,j)=><p className="small-warning" key={j}>{w}</p>)}{m.scope&&<p className="scope-text">{m.scope}</p>}</div>)}{busy&&<div className="thinking"><LoaderCircle size={15} className="spin"/>{status||'正在处理…'}</div>}<div ref={chatEnd}/></div><div className="composer"><label className="sr-only" htmlFor="question">向论文提问</label><textarea id="question" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="带着原文，问一个问题…" maxLength={5000} rows={3} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();void ask('ask');}}}/><div className="composer-bottom"><span>Ctrl / ⌘ + Enter</span>{busy?<button className="send stop" onClick={stop} aria-label="停止生成"><StopCircle size={18}/></button>:<button className="send" disabled={!question.trim()} onClick={()=>void ask('ask')} aria-label="发送问题"><ArrowUp size={19}/></button>}</div><p>AI 回答可能有误，请通过引用核对原文。</p></div></>}{!connected&&<button className="connection-banner" onClick={()=>setConnectOpen(true)}><Settings2 size={14}/>{statusError||'AI 服务待连接'}<ArrowUpRight size={13}/></button>}</>;
 return <><header className="topbar"><a className="brand" href="/" aria-label="Paper Room 首页"><span className="logo">P</span>Paper Room<span className="slash">/</span><b>论文阅读室</b></a><span className="header-note">READ · UNDERSTAND · QUESTION</span><div className="header-actions"><button className={`connection-status ${connected?'ready':''}`} onClick={()=>setConnectOpen(true)}>{connected?<Check size={14}/>:<Settings2 size={14}/>}<span>{connected?'AI 已配置':'连接 AI'}</span></button>{paper&&<button className="new-paper" disabled={busy||importing} onClick={()=>{setError('');setImportOpen(true);}}><Plus size={16}/><span>导入论文</span></button>}</div></header><SidebarProvider className="site-sidebar-provider"><div className="workspace"><Sidebar collapsible="none" className="paper-nav"><div className="nav-heading">{paper?'论文章节':'阅读目录'}<span>{paper?`${paper.pages.length} 节`:'CONTENTS'}</span></div><SidebarContent>{paper?<SidebarMenu className="page-menu">{paper.pages.map((p,i)=><SidebarMenuItem key={p.number}><SidebarMenuButton isActive={i===page} onClick={()=>goTo(i)} className="page-menu-button"><span className="page-number">{String(p.number).padStart(2,'0')}</span><span className="page-label">{p.label}</span>{p.blocks.length>0&&p.blocks.every(b=>translations[b.id])&&<Check size={13}/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>:<div className="nav-empty"><BookOpen size={22}/><p>导入论文后，<br/>从这里开始阅读。</p></div>}</SidebarContent><div className="nav-bottom">{paper?<><div className="progress-label"><span>已翻译</span><b>{completePages} / {paper.pages.length} 节</b></div><Progress value={completePages/paper.pages.length*100} className="h-1" aria-label="全文翻译进度"/></>:<span>让每一次阅读<br/>都有更深一层的理解。</span>}</div></Sidebar><main className={`reader-main ${paper?'has-paper':''}`}>
 {error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={()=>setError('')} aria-label="关闭错误提示"><X size={16}/></button></div>}
 {!paper?<><div className="eyebrow">YOUR NEXT PAPER</div><h1>把论文读懂，<br/><em>从这里开始。</em></h1><p className="intro">原文在左，理解在旁。带着问题读每一段。</p>{importForm}<p className="privacy-note">文件在浏览器中读取。使用 AI 时，相关文本和页面图像会发送至所选模型服务商；本次阅读保留在当前页面，刷新后需重新导入。</p><div className="capabilities"><div><Languages/><b>对照翻译</b><p>逐段对应，核对术语与公式。</p></div><div><BookOpen/><b>内容讲解</b><p>从核心观点走到推导细节。</p></div><div><Quote/><b>选段提问</b><p>引用原文，让问题更具体。</p></div></div></>:<><div className="document-eyebrow"><span>{paper.kind==='pdf'?'PDF PAPER':'TEXT PAPER'}</span><span>{paper.pages.length} {paper.kind==='pdf'?'节':'个片段'}</span></div><h1 className="document-title">{paper.title}</h1><div className="document-actions"><div>{paper.url&&<a href={paper.url} target="_blank" rel="noopener">打开原 PDF <ArrowUpRight size={14}/></a>}<span>第 {page+1} / {paper.pages.length} 节</span></div><div className="page-controls"><button disabled={page===0} onClick={()=>goTo(page-1)} aria-label="上一节"><ChevronLeft size={18}/></button><button disabled={page===paper.pages.length-1} onClick={()=>goTo(page+1)} aria-label="下一节"><ChevronRight size={18}/></button></div></div>
 <div className="reading-toolbar"><Tabs value={mode} onValueChange={setMode}><TabsList><TabsTrigger value="both">中英对照</TabsTrigger><TabsTrigger value="original">原文</TabsTrigger>{paper.kind==='pdf'&&<TabsTrigger value="pdf">原页</TabsTrigger>}</TabsList></Tabs><button className="explain-page" disabled={busy} onClick={()=>{void ask('explain');if(window.innerWidth<931)showPanel();}}><Sparkles size={15}/>讲解本节</button></div>
 <div className="translation-actions"><button className="primary" disabled={busy||current?.scanned} onClick={()=>void translate()}><Languages size={15}/>翻译本节</button><button className="secondary" disabled={busy||completePages===paper.pages.length} onClick={()=>void translate(true)}>翻译全文</button>{busy&&<button className="text-button" onClick={stop}><StopCircle size={14}/>停止</button>}<span>{connected?'保留公式、数字和不确定性':'连接 AI 后可翻译与提问'}</span></div>
 {status&&<div className="work-status" role="status">{busy&&<LoaderCircle size={14} className="spin"/>}{status}</div>}
 {paper.kind==='pdf'&&!current?.blocks.some(b=>b.page===sourcePage)&&<div className="scan-notice"><ScanText size={22}/><div><b>原第 {sourcePage} 页没有足够的可选文字</b><p>可查看原页，或使用 AI 识别这一页的文字。</p><button disabled={busy} onClick={()=>void ocr()}>识别本页文字 <ArrowUpRight size={14}/></button></div></div>}
 {paper.kind==='pdf'&&mode!=='pdf'&&<details className="inline-pdf" open><summary>原页图表与公式 · 第 {sourcePage} 页 <span>点击折叠 / 展开</span></summary><div className="inline-pdf-content">{sourcePages.length>1&&<div className="source-pages"><span>原页：</span>{sourcePages.map(n=><button key={n} className={n===sourcePage?'active':''} onClick={()=>setSourcePage(n)}>{n}</button>)}</div>}{imageLoading?<div className="loading-state"><LoaderCircle className="spin"/>正在显示图表…</div>:pageImage?<><button type="button" onClick={()=>setMode('pdf')} title="切换到原页视图"><img src={pageImage} alt={`论文第 ${sourcePage} 页原版，包括图表、公式和排版`}/></button><p>点击图像切换到原页视图；需要更大画面可用“打开原 PDF”。</p></>:<>{paper.url?<iframe title={`论文第 ${sourcePage} 页原版`} src={`${paper.url}#page=${sourcePage}`} />:<p>{imageError||'原页暂不可用。'}</p>}</>}</div></details>}
 {mode==='pdf'?<div className="pdf-preview">{imageLoading?<div className="loading-state"><LoaderCircle className="spin"/>正在显示原页…</div>:pageImage?<img src={pageImage} alt={`原论文第 ${sourcePage} 页`}/>:<p>{imageError||'此页预览不可用。'}</p>}</div>:<div className="paragraphs">{current?.blocks.map((b,i)=><section className={`paper-block ${selected.includes(b.id)||excerpt?.ids.includes(b.id)?'selected':''}`} id={b.id} data-paper-block={b.id} key={b.id}><div className="block-header"><Checkbox checked={selected.includes(b.id)} onCheckedChange={on=>toggleBlock(b.id,on===true)} aria-label={`引用第 ${b.page} 页第 ${i+1} 段`}/><span>原文 <span className="block-num">{String(i+1).padStart(2,'0')}</span></span><span className="block-source">p. {b.page} · {b.id}</span></div><div className="source-text">{b.text}</div>{mode==='both'&&<div className={`translation ${translations[b.id]?'filled':''}`}><div className="translation-label"><span>译</span>{translations[b.id]?'中文译文':'等待翻译'}</div>{translations[b.id]?<RichText text={translations[b.id]}/>:<p>点击“翻译本节”，在这里对照阅读中文译文。</p>}</div>}</section>)}</div>}
 {(pageNotes[page+1]||[]).length>0&&<div className="translation-notes"><b>需要核对</b>{pageNotes[page+1].map((n,i)=><p key={i}>{n}</p>)}</div>}
 {paper.kind==='pdf'&&sourcePages.length>1&&<div className="source-pages"><span>本节原页：</span>{sourcePages.map(n=><button key={n} className={n===sourcePage?'active':''} onClick={()=>setSourcePage(n)}>{n}</button>)}</div>}<div className="bottom-pagination"><button disabled={page===0} onClick={()=>goTo(page-1)}><ChevronLeft size={15}/>上一节</button><span>{page+1} / {paper.pages.length} 节</span><button disabled={page===paper.pages.length-1} onClick={()=>goTo(page+1)}>下一节<ChevronRight size={15}/></button></div><p className="reading-footnote">PDF 文字可能有分栏或公式识别误差，请切换“原页”核对。AI 译文与讲解不替代原文。</p></>}
 </main><aside className="assistant-panel">{panel}</aside></div></SidebarProvider>
 <Dialog open={importOpen} onOpenChange={setImportOpen}><DialogContent className="import-dialog"><DialogHeader><DialogTitle>导入一篇新论文</DialogTitle><DialogDescription>新论文会替换当前阅读内容与问答记录。</DialogDescription></DialogHeader>{error&&<p className="dialog-error">{error}</p>}{importForm}</DialogContent></Dialog>
 <Dialog open={connectOpen} onOpenChange={setConnectOpen}><DialogContent><DialogHeader><DialogTitle>连接论文助手</DialogTitle><DialogDescription>选择服务商并填入对应的 API Key，即可使用翻译、讲解和选段提问。</DialogDescription></DialogHeader><div className="connection-detail"><label className="field-label" htmlFor="ai-provider">模型服务</label><select id="ai-provider" className="text-input" value={provider} onChange={e=>{setProvider(e.target.value as 'deepseek'|'openai');setApiKey('');}}><option value="deepseek">DeepSeek（deepseek-flash）</option><option value="openai">OpenAI</option></select><label className="field-label" htmlFor="openai-key">{provider==='deepseek'?'DeepSeek':'OpenAI'} API Key</label><input id="openai-key" className="text-input" type="password" autoComplete="off" spellCheck={false} value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="sk-…"/><p className="privacy-note">仅保留在当前页面内存中，刷新即清除。发起请求时，密钥由本站服务用于向所选模型服务发起请求；请只在你信任的设备上输入。调用可能产生所选服务商的 API 费用。</p>{provider==='openai'&&configured&&<p>站点也已配置 OpenAI 模型服务；留空可使用站点配置。</p>}{statusError&&<p role="alert">{statusError}</p>}<div className="key-actions"><button className="secondary" onClick={()=>setApiKey('')} disabled={!apiKey}>清除密钥</button><button className="primary" onClick={()=>setConnectOpen(false)} disabled={!connected}>完成</button></div></div></DialogContent></Dialog>
 <Sheet open={mobileOpen} onOpenChange={setMobileOpen}><SheetContent side="right" className="mobile-assistant"><SheetHeader className="sr-only"><SheetTitle>论文助手</SheetTitle><SheetDescription>查看引用原文并提问。</SheetDescription></SheetHeader>{panel}</SheetContent></Sheet>
 {paper&&<button className="mobile-question" onClick={showPanel}><PanelRightOpen size={17}/>选段提问{chosen.length>0&&<span>{chosen.length}</span>}</button>}
 {pending&&<button className="selection-popover" onPointerDown={e=>e.preventDefault()} onClick={selectExcerpt}><Quote size={15}/>引用选中文字<ArrowUpRight size={14}/></button>}
 </>;
}
